apiVersion: v1
kind: Secret
metadata:
  name: langfuse-general
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  salt: {{ .Values.secrets.langfuse.salt | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-nextauth-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  nextauth-secret: {{ .Values.secrets.langfuse.nextAuthSecret | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-encryption
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  encryption-key: {{ .Values.secrets.langfuse.encryptionKey | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-postgresql-auth
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.secrets.postgres.password | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-clickhouse-auth
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.secrets.clickhouse.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-redis-auth
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.secrets.redis.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-minio-auth
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  root-user: {{ .Values.secrets.minio.rootUser | quote }}
  root-password: {{ .Values.secrets.minio.rootPassword | quote }}

{{- if .Values.secrets.azure.ad.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-azure-ad
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  client-id: {{ .Values.secrets.azure.ad.clientId | quote }}
  client-secret: {{ .Values.secrets.azure.ad.clientSecret | quote }}
  tenant-id: {{ .Values.secrets.azure.ad.tenantId | quote }}
{{- end }}

{{- if .Values.secrets.azure.blob.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-azure-blob
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  storageAccountName: {{ .Values.secrets.azure.blob.storageAccountName | quote }}
  storageAccountKey: {{ .Values.secrets.azure.blob.storageAccountKey | quote }}
{{- end }}

{{- if .Values.secrets.gcs.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-gcs-blob
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  serviceAccountCredentials: {{ .Values.secrets.gcs.serviceAccountCredentials | quote }}
{{- end }}
